//
//  RevealQuestionModels.swift
//  RemoteConfigs
//
//  Created by Zaim Ramlan on 29/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RevealQuestionModels {
  
  // MARK: Use Cases
  
  enum RevealQuestion {
    struct Request {
    }

    struct Response {
      var question: String?
    }

    struct ViewModel {
      var question: String?
    }
  }
  
  enum SubmitAnswer {
    struct Request {
      var answer: String?
    }
    
    struct Response {
      var isCorrect: Bool
    }
    
    struct ViewModel {
      var isCorrect: Bool
    }
  }
  
  // MARK: View Models
  
  enum ToggleViewType {
    case withAnimation, withoutAnimation
  }
}
