//
//  RevealQuestionRouter.swift
//  RemoteConfigs
//
//  Created by Zaim Ramlan on 29/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevealQuestionRoutingLogic {
  func routeToSomewhere()
}

protocol RevealQuestionDataPassing {
  var dataStore: RevealQuestionDataStore? { get }
}

class RevealQuestionRouter: NSObject, RevealQuestionRoutingLogic, RevealQuestionDataPassing {
  var viewController: RevealQuestionViewController?
  var dataStore: RevealQuestionDataStore?
  
  // MARK: Routing

  func routeToSomewhere() {
    routeToSomewhere(segue: nil)
  }
  
  func routeToSomewhere(segue: UIStoryboardSegue?) {
    if let segue = segue {
      let destinationVC = segue.destination as! RevealQuestionViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
    } else {
      let destinationVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "SomewhereViewController") as! RevealQuestionViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataTo(&destinationDS, from: dataStore!)
      viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
  }
  
  // MARK: Data Passing
  
  func passDataTo(_ destinationDS: inout RevealQuestionDataStore, from sourceDS: RevealQuestionDataStore) {
    destinationDS.attribute = sourceDS.attribute
  }
}
