//
//  RevealQuestionRouter.swift
//  RemoteConfigs
//
//  Created by Zaim Ramlan on 29/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevealQuestionRoutingLogic {
}

protocol RevealQuestionDataPassing {
  var dataStore: RevealQuestionDataStore? { get }
}

class RevealQuestionRouter: NSObject, RevealQuestionRoutingLogic, RevealQuestionDataPassing {
  var viewController: RevealQuestionViewController?
  var dataStore: RevealQuestionDataStore?
  
  // MARK: Routing
}
