//
//  RevealQuestionPresenter.swift
//  RemoteConfigs
//
//  Created by Zaim Ramlan on 29/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevealQuestionPresentationLogic {
  func presentFetchFromDataStoreResult(with response: RevealQuestionModels.FetchFromDataStore.Response)
  func presentRevealQuestionResult(with response: RevealQuestionModels.RevealQuestion.Response)
}

class RevealQuestionPresenter: RevealQuestionPresentationLogic {
  weak var viewController: RevealQuestionDisplayLogic?

  // MARK: Fetch Data From DataStore
  
  func presentFetchFromDataStoreResult(with response: RevealQuestionModels.FetchFromDataStore.Response) {
    let viewModel = RevealQuestionModels.FetchFromDataStore.ViewModel(userAttribute: response.userAttribute)
    viewController?.displayFetchFromDataStoreResult(with: viewModel)
  }  
  
  // MARK: Use Case - RevealQuestion
  
  func presentRevealQuestionResult(with response: RevealQuestionModels.RevealQuestion.Response) {
    let viewModel = RevealQuestionModels.RevealQuestion.ViewModel(containsErrors: response.containsErrors, genericErrorMessage: response.genericErrorMessage, variablePassed: response.variablePassed)
    viewController?.displayRevealQuestionResult(with: viewModel)
  }
}
