//
//  RevealQuestionPresenter.swift
//  RemoteConfigs
//
//  Created by Zaim Ramlan on 29/04/2018.
//  Copyright (c) 2018 ZaimRamlan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevealQuestionPresentationLogic {
  func presentRevealQuestionResult(with response: RevealQuestionModels.RevealQuestion.Response)
  func presentSubmitAnswerResult(with response: RevealQuestionModels.SubmitAnswer.Response)
}

class RevealQuestionPresenter: RevealQuestionPresentationLogic {
  weak var viewController: RevealQuestionDisplayLogic?
  
  // MARK: Use Case - Reveal Question
  
  func presentRevealQuestionResult(with response: RevealQuestionModels.RevealQuestion.Response) {
    let viewModel = RevealQuestionModels.RevealQuestion.ViewModel(question: response.question)
    viewController?.displayRevealQuestionResult(with: viewModel)
  }
  
  // MARK: Use Case - Submit Answer
  
  func presentSubmitAnswerResult(with response: RevealQuestionModels.SubmitAnswer.Response) {
    let viewModel = RevealQuestionModels.SubmitAnswer.ViewModel(isCorrect: response.isCorrect)
    viewController?.displaySubmitAnswerResult(with: viewModel)
  }
}
